### ISSUE TITLE
Possible comparison typo in RF24Client.cpp

### ISSUE THREAD

**Issue by kluzzebass** [TMRh20/RF24Ethernet#10]
I was browsing the code and came across this little tidbit:

`bool RF24Client::operator==(const RF24Client& rhs) {
  return data && rhs.data && (data = rhs.data);
}`

I think perhaps it should be `data == rhs.data`, or is the assignment intentional?

**Comment by TMRh20** [comment]
I think so, and checked [UIPEthernet](https://github.com/ntruchsess/arduino_uip/blob/master/UIPClient.cpp#L145) for comparison. Thanks.
