### ISSUE TITLE
None of the arduino example sketches connect to gateway

### ISSUE THREAD

**Issue by andreibosco** [TMRh20/RF24Ethernet#15]
Hello. I've spent the evening reading the docs, checking your youtube videos and reading the comments in the arduino sketches to check if I've been missing something but I just can't get the RF24Ethernet examples to connect to a RF24Gateway running on a raspberry pi.

The sketches compile and upload fine, but they don't register with the gateway (nothing shows up on 'Mesh Info') and it only outputs 'start' to the serial monitor. The interesting thing is that If I use of one the RF24Mesh examples the arduino node shows up on the gateway list.

**Comment by TMRh20** [comment]
Can you please try editing the RF24Mesh.cpp file and comment out or remove the line here:
https://github.com/TMRh20/RF24Mesh/blob/master/RF24Mesh.cpp#L17

**Comment by andreibosco** [comment]
Now everything works beautifully. Thanks for replying so fast.

**Comment by TMRh20** [comment]
Np, thanks for reporting & testing this.
